# Generated by Django 5.2.6 on 2025-09-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sobre', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryCard',
            new_name='CardsHistoria',
        ),
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Membros',
        ),
        migrations.RenameModel(
            old_name='ValueItem',
            new_name='Valores',
        ),
    ]
