# Generated by Django 5.2.6 on 2025-09-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_category_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
