# Generated by Django 5.2.6 on 2025-09-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_siteconfiguration_delete_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='address',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='phone',
            new_name='telefone',
        ),
    ]
