# Generated by Django 5.2.6 on 2025-09-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_planos_usuario_usuario_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sumario', models.TextField()),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, max_length=255, null=True, upload_to='noticias/')),
                ('data_publicacao', models.DateTimeField()),
                ('destaque', models.BooleanField(default=False)),
                ('categoria', models.CharField(max_length=100)),
                ('tipo_modal', models.CharField(blank=True, choices=[('autoopen', 'Abrir automático'), ('updade_notification', 'Notificação Atualizada')], max_length=30, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='pagina.usuario')),
            ],
        ),
    ]
