# Generated by Django 5.2.6 on 2025-09-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaSobreNos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo_midia', models.CharField(choices=[('video', 'video'), ('foto', 'foto')], max_length=20, verbose_name='Tipo de Mídia')),
                ('midia_url', models.CharField(max_length=255, verbose_name='URL da mídia')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
