# Generated by Django 5.2.6 on 2025-09-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_seed_planos'),
    ]

    operations = [
        migrations.CreateModel(
            name='avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('texto_avaliacao', models.TextField()),
                ('imagem', models.ImageField(upload_to='pasta')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='planos',
            name='tipo',
        ),
    ]
