# Generated by Django 5.2.6 on 2025-09-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_avaliacoes_remove_planos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planos',
            options={'ordering': ['preco']},
        ),
    ]
