# Generated by Django 5.2.6 on 2025-09-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_alter_planos_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beneficio',
        ),
    ]
