# Generated by Django 5.2.6 on 2025-09-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_delete_beneficio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='endereco',
            new_name='rua_bairro',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='cidade',
            field=models.CharField(default='Natal - RN', max_length=100),
            preserve_default=False,
        ),
    ]
