# Generated by Django 5.2.6 on 2025-09-16 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_rename_endereco_siteconfiguration_rua_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato +DD XX XXXXX-XXXX', regex='^\\+\\d{1,3} \\d{2,5}-\\d{4}$')]),
        ),
    ]
