# Generated by Django 5.2.6 on 2025-09-16 23:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0013_alter_siteconfiguration_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
