# Generated by Django 5.2.6 on 2025-09-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0014_alter_siteconfiguration_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
