# Generated by Django 5.2.6 on 2025-09-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0015_alter_siteconfiguration_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua_bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
