# Generated by Django 5.2.6 on 2025-09-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0016_informacoes_delete_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoes',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='informacoes',
            name='rua_bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoes',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
