# Generated by Django 5.2.6 on 2025-09-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0017_alter_informacoes_cidade_alter_informacoes_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='icone_url',
        ),
        migrations.AddField(
            model_name='planos',
            name='image',
            field=models.ImageField(default='planos/default.jpg', upload_to='pasta_pl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacoes',
            name='imagem',
            field=models.ImageField(upload_to='pasta_av'),
        ),
    ]
