# Generated by Django 5.2.6 on 2025-09-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0018_remove_planos_icone_url_planos_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('sobre_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sobre_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('sobre_texto', models.TextField(blank=True, null=True)),
                ('sobre_imagem', models.ImageField(blank=True, null=True, upload_to='quem_somos/')),
            ],
        ),
    ]
