# Generated by Django 5.2.6 on 2025-09-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0019_siteconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='endereco',
            new_name='beneficios_titulo',
        ),
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='facebook',
            new_name='preco_botao_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='youtube',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='preco_botao_texto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='preco_disclaimer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='preco_titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='preco_valor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='beneficios/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='pagina.siteconfiguration')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
