# Generated by Django 5.2.6 on 2025-09-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0020_rename_endereco_siteconfiguration_beneficios_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_blog_link',
            field=models.URLField(blank=True, default='#blog', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_home_link',
            field=models.URLField(blank=True, default='#home', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_noticias_link',
            field=models.URLField(blank=True, default='#noticias', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_sobre_link',
            field=models.URLField(blank=True, default='#sobre', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_testar_link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
