# Generated by Django 5.2.6 on 2025-09-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0021_siteconfiguration_navbar_blog_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='beneficios_titulo',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='beneficios_parte1',
            field=models.CharField(blank=True, default='Benefícios', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='beneficios_parte2',
            field=models.CharField(blank=True, default='do nosso plano', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='beneficios_parte3',
            field=models.CharField(blank=True, default='Angelical', max_length=255, null=True),
        ),
    ]
