# Generated by Django 5.2.6 on 2025-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0022_remove_siteconfiguration_beneficios_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='navbar_blog_link',
            field=models.CharField(blank=True, default='/blog', max_length=200, null=True),
        ),
    ]
