# Generated by Django 5.2.6 on 2025-09-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0023_alter_siteconfiguration_navbar_blog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='navbar_home_link',
            field=models.CharField(blank=True, default='/home', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='navbar_noticias_link',
            field=models.CharField(blank=True, default='/noticias', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='navbar_sobre_link',
            field=models.CharField(blank=True, default='/sobre', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='navbar_testar_link',
            field=models.CharField(blank=True, default='/testar', max_length=200, null=True),
        ),
    ]
